//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace IcerDesign.CCHelper {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class CCHelperProfile {
        
        private CCHelperProfileSession[] sessionsField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Session", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CCHelperProfileSession[] Sessions {
            get {
                return this.sessionsField;
            }
            set {
                this.sessionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CCHelperProfileSession {
        
        private string sourceFilterField;
        
        private string destFilterField;
        
        private string nameField;
        
        private string sourceURLField;
        
        private string sourceBranchField;
        
        private string destPathField;
        
        private string sourceBasePathField;
        
        private bool filterDestSameAsSourceField;
        
        private bool filterDestSameAsSourceFieldSpecified;
        
        private string sourceUsernameField;
        
        private string sourcePasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SourceFilter {
            get {
                return this.sourceFilterField;
            }
            set {
                this.sourceFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DestFilter {
            get {
                return this.destFilterField;
            }
            set {
                this.destFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SourceURL {
            get {
                return this.sourceURLField;
            }
            set {
                this.sourceURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SourceBranch {
            get {
                return this.sourceBranchField;
            }
            set {
                this.sourceBranchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DestPath {
            get {
                return this.destPathField;
            }
            set {
                this.destPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SourceBasePath {
            get {
                return this.sourceBasePathField;
            }
            set {
                this.sourceBasePathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool FilterDestSameAsSource {
            get {
                return this.filterDestSameAsSourceField;
            }
            set {
                this.filterDestSameAsSourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FilterDestSameAsSourceSpecified {
            get {
                return this.filterDestSameAsSourceFieldSpecified;
            }
            set {
                this.filterDestSameAsSourceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SourceUsername {
            get {
                return this.sourceUsernameField;
            }
            set {
                this.sourceUsernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SourcePassword {
            get {
                return this.sourcePasswordField;
            }
            set {
                this.sourcePasswordField = value;
            }
        }
    }
}
